/**
 * Link-to-article scaffold + pipeline handoff (POK-421 / POK-426).
 */

import { mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { ingestLink } from "./ingest-router.mjs";
import { formatSourceMaterial } from "./format-source-material.mjs";
import { buildManifestYaml, parseManifest, validateManifest } from "./manifest-schema.mjs";
import { slugFromUrl, isValidSlug } from "./slug-from-url.mjs";

const EXPORT_PROMPTS = {
  medium: "prompts/04-export-medium.md",
  tommarler: "prompts/05-export-tommarler.md",
  x: "prompts/06-export-x.md",
};

const EXPORT_PATHS = {
  medium: (slug) => `export/medium/${slug}.md`,
  tommarler: (slug) => `export/tommarler/${slug}.md`,
  x: (slug) => `export/x/${slug}/thread.md`,
};

export function buildCursorPrompts(slug, channels) {
  const prompts = [
    {
      step: "draft",
      file: "prompts/07-draft-from-link.md",
      message: `Follow \`prompts/07-draft-from-link.md\` for slug \`${slug}\`.`,
    },
    {
      step: "self-edit",
      file: "prompts/03-self-edit.md",
      message: `Follow \`prompts/03-self-edit.md\` for slug \`${slug}\`.`,
    },
  ];

  for (const channel of channels) {
    const promptFile = EXPORT_PROMPTS[channel];
    if (promptFile) {
      prompts.push({
        step: `export-${channel}`,
        file: promptFile,
        message: `Follow \`${promptFile}\` for slug \`${slug}\`.`,
      });
    }
  }

  return prompts;
}

export function buildHandoffMarkdown({ slug, channels, cursorPrompts }) {
  const exportLines = channels
    .map((c) => `- \`${EXPORT_PATHS[c]?.(slug) ?? `export/${c}/${slug}`}\``)
    .join("\n");

  const promptLines = cursorPrompts
    .map((p, i) => `${i + 1}. ${p.message}`)
    .join("\n");

  return `# Drop-link handoff: ${slug}

Generated by \`draftsmith new\`. Run these Cursor chat steps in order (prompts are not shell commands):

${promptLines}

## Output locations

\`\`\`text
articles/drafts/${slug}/
├── manifest.yaml
├── source-material.md
├── draft.md          ← step 1
├── draft-v2.md       ← step 2
\`\`\`

Exports (step 3+):

${exportLines}

See [\`docs/drop-link.md\`](../../../docs/drop-link.md).
`;
}

/**
 * Ingest URL, write manifest + source material, validate, write handoff.
 */
export async function scaffoldLinkDraft({
  url,
  slug: slugInput = null,
  title = null,
  channels = ["medium"],
  angle = null,
  series = null,
  part = null,
  engine = "auto",
  rootDir = process.cwd(),
}) {
  const slug = slugInput ?? slugFromUrl(url);
  if (!isValidSlug(slug)) {
    throw new Error(`slug: invalid kebab-case "${slug}" (pass --slug explicitly)`);
  }

  const payload = await ingestLink(url, { engine });
  const resolvedTitle = title || payload.title;
  const draftDir = join(rootDir, "articles", "drafts", slug);

  mkdirSync(draftDir, { recursive: true });

  const sourceMaterial = formatSourceMaterial({
    url: payload.url,
    linkType: payload.link_type,
    title: payload.title,
    markdown: payload.markdown,
    engine: payload.engine,
  });

  const manifestYaml = buildManifestYaml({
    slug,
    title: resolvedTitle,
    channels,
    sourceUrl: payload.url,
    linkType: payload.link_type,
    angle,
    series,
    part,
  });

  const manifestPath = join(draftDir, "manifest.yaml");
  const sourceMaterialPath = join(draftDir, "source-material.md");
  const handoffPath = join(draftDir, "handoff.md");

  writeFileSync(sourceMaterialPath, sourceMaterial, "utf8");
  writeFileSync(manifestPath, manifestYaml, "utf8");

  const manifest = parseManifest(manifestYaml);
  const validation = validateManifest(manifest, slug, { draftDir });

  if (!validation.ok) {
    throw new Error(validation.errors.join("; "));
  }

  const cursorPrompts = buildCursorPrompts(slug, channels);
  writeFileSync(
    handoffPath,
    buildHandoffMarkdown({ slug, channels, cursorPrompts }),
    "utf8"
  );

  return {
    slug,
    draftDir,
    manifestPath,
    sourceMaterialPath,
    handoffPath,
    linkType: payload.link_type,
    title: resolvedTitle,
    channels,
    sourceLength: payload.markdown.length,
    engine: payload.engine,
    cursorPrompts,
    validation,
  };
}

export function getPipelineStatus(slug, rootDir = process.cwd()) {
  const draftDir = join(rootDir, "articles", "drafts", slug);
  const manifestPath = join(draftDir, "manifest.yaml");

  if (!existsSync(manifestPath)) {
    return { slug, exists: false, draftDir };
  }

  const manifest = parseManifest(readFileSync(manifestPath, "utf8"));
  const channels = manifest.channels ?? [];

  const files = {
    manifest: existsSync(manifestPath),
    sourceMaterial: existsSync(join(draftDir, "source-material.md")),
    handoff: existsSync(join(draftDir, "handoff.md")),
    draft: existsSync(join(draftDir, "draft.md")),
    draftV2: existsSync(join(draftDir, "draft-v2.md")),
  };

  const exports = {};
  for (const channel of channels) {
    const path = EXPORT_PATHS[channel]?.(slug);
    exports[channel] = path ? existsSync(join(rootDir, path)) : false;
  }

  let nextStep = null;
  if (!files.draft) {
    nextStep = buildCursorPrompts(slug, channels)[0];
  } else if (!files.draftV2) {
    nextStep = buildCursorPrompts(slug, channels)[1];
  } else {
    const missingExport = channels.find((c) => !exports[c]);
    if (missingExport) {
      nextStep = buildCursorPrompts(slug, channels).find(
        (p) => p.step === `export-${missingExport}`
      );
    }
  }

  return {
    slug,
    exists: true,
    draftDir,
    manifest,
    files,
    exports,
    nextStep,
  };
}
